baseurl             = "/"
languageCode        = "en-us"
title               = "Introduction"
theme               = "hugo-theme-introduction"
enforce_ssl         = ""
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
layoutdir           = "layouts"
publishdir          = "public"
# disqusshortname   = "xxx" # Enable Disqus for comments
# googleAnalytics   = "xxx"

[permalinks]
fixed = ":title/"
blog  = "blog/:slug/"

[params]
author        = "Pauline Chin" # Full name shows on blog post pages
firstname     = "Pauline" # First name shows in introduction on main page
tagline       = "Netifly Exercise" # Appears after the introduction
introheight   = "medium" # Input either 'medium' or 'large' or 'fullheight'
avatar        = "http://www.paulinechin.com/images/paulinechin500x500.jpg" # Path to image in static folder eg. img/avatar.png
email         = "hello@paulinechin.com" # Shows in contact section, or leave blank to omit
dateform      = "19 April, 2017"
dateformfull  = "Mon Jan 2 2006 15:04:05 EST"
cachebuster   = true # Add the current unix timestamp in query string for cache busting css assets
description   = "Website Description"
faviconfile   = "img/fav.ico"
highlightjs   = true # Syntax highlighting
lang          = "en"
footertext    = "" # Text to show in footer (overrides default text)

# Social icons appear in introduction and contact section. Input your username only, eg "you" as it appears in "twitter.com/you"
linkedin      = "http://linkedin.com/in/paulinechin"
twitter       = "https://twitter.com/nomadpauline"
github        = "you"
codepen       = "you"
pinterest     = ""
facebook      = ""
googleplus    = ""

showblog        = false # Show Blog section on home page
showallposts    = false # Set 'true' to list all posts on home page, or set 'false' to link to separate blog list page
showlatest      = false # Show latest blog post summary
sharebuttons    = false # On post pages, show share this social buttons

showprojects    = false # Show Projects section on home page

# This is your projects section. Three images of the same dimensions will look the nicest. If images are omitted, text links will be shown.
project1link    = "#"
project1img     = "img/project1.jpg"
project1title   = "Project 1"

project2link    = "#"
project2img     = "img/project2.jpg"
project2title   = "Project 2"

project3link    = "#"
project3img     = "img/project3.jpg"
project3title   = "Project 3"
